use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::net::IpAddr;
use std::path::PathBuf;

/// Main configuration structure (maps from NixOS options)
///
/// `deny_unknown_fields` on every struct here (and on `DhcpInterface`,
/// `AutoinstallScript`, `HttpConfig` below): this JSON is generated by
/// the Nix module, not hand-written -- a field-name typo introduced by
/// a refactor on either side (Nix emitting a renamed/misspelled key, or
/// a Rust struct field rename that didn't update the Nix side) would
/// otherwise be silently swallowed by serde's default permissive
/// deserialization instead of failing fast at config-load time.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PxeBootConfig {
    /// Path to folder containing ISO files
    pub iso_folder_path: PathBuf,

    /// TFTP root folder (default: /srv/pxeboot)
    pub tftp_root: PathBuf,

    /// Runtime folder (default: /run/pxe-boot)
    pub runtime_root: PathBuf,

    /// DHCP interfaces with PXE boot enabled
    pub dhcp_interfaces: Vec<DhcpInterface>,

    /// Autoinstall scripts mapped to ISOs
    #[serde(default)]
    pub autoinstall: HashMap<String, Vec<AutoinstallScript>>,

    /// HTTP server configuration
    pub http: HttpConfig,
}

/// DHCP interface configuration
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct DhcpInterface {
    pub id: u32,
    pub name: String,
    pub gateway: IpAddr,
    pub default_iso: Option<String>,
    pub default_script: Option<String>,

    /// Per-interface override of `PxeBootConfig::tftp_root`. `None` (the
    /// default) falls back to that global root.
    #[serde(default)]
    pub tftp_root: Option<PathBuf>,
}

/// Autoinstall script definition
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct AutoinstallScript {
    pub name: String,
    pub script_path: PathBuf,
}

/// HTTP server configuration
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct HttpConfig {
    /// Single port serving both the GRUB/kernel/initrd tree
    /// (`runtime_root`, at `/`) and raw whole-ISO downloads (the
    /// canonical `runtime_root/isos/` symlink tree, at `/isos/`) --
    /// previously two separate ports/processes (one darkhttpd instance
    /// per root), collapsed once the HTTP server itself (nginx) gained
    /// native multi-root support.
    pub port: u16, // default: 1337
}

/// Discovered ISO information
#[derive(Debug, Clone)]
pub struct IsoInfo {
    pub file_name: String,
    pub file_path: PathBuf,
    pub mount_path: PathBuf,
    pub distro_type: DistroType,
    pub kernel_path: PathBuf,
    pub initrd_path: PathBuf,
}

impl IsoInfo {
    /// Placeholder constructed before distro detection has run --
    /// `distro_type`/`kernel_path`/`initrd_path` are unknown until
    /// `apply_boot_info` below fills them in from a successful
    /// `DistroDetector::extract_boot_info` call.
    pub fn placeholder(file_name: String, file_path: PathBuf, mount_path: PathBuf) -> Self {
        Self {
            file_name,
            file_path,
            mount_path,
            distro_type: DistroType::Unknown(String::new()),
            kernel_path: PathBuf::new(),
            initrd_path: PathBuf::new(),
        }
    }

    /// Copies the fields `IsoInfo` and `BootInfo` share. Centralizing
    /// this in one place means every call site that builds an `IsoInfo`
    /// placeholder before detection stays in sync with `BootInfo` by
    /// construction -- two call sites in `lib.rs` had already drifted
    /// from each other this way (one copied `kernel_path`/`initrd_path`
    /// too, the other only `distro_type`, because it happened not to
    /// need the rest yet), which is exactly the kind of silent
    /// divergence a hand-written copy at N call sites invites.
    pub fn apply_boot_info(&mut self, boot_info: &BootInfo) {
        self.distro_type = boot_info.distro_type.clone();
        self.kernel_path = boot_info.kernel_path.clone();
        self.initrd_path = boot_info.initrd_path.clone();
    }
}

/// Distribution type enumeration
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DistroType {
    NixOS,
    Ubuntu,
    RedHat,
    Unknown(String),
}

/// Boot information extracted from ISO
#[derive(Debug, Clone)]
pub struct BootInfo {
    pub kernel_path: PathBuf,
    pub initrd_path: PathBuf,
    pub distro_type: DistroType,
    pub version: Option<String>,
    pub architecture: Option<String>,
}

/// GRUB menu entry
#[derive(Debug, Clone)]
pub struct MenuEntry {
    pub title: String,
    pub kernel_url: String,
    pub kernel_params: Vec<String>,
    pub initrd_url: String,
    pub position: usize,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn placeholder_has_unknown_distro_and_empty_boot_paths() {
        let iso_info = IsoInfo::placeholder(
            "test.iso".to_string(),
            PathBuf::from("/isos/test.iso"),
            PathBuf::from("/run/pxe-boot/iso-mountpoint/test.iso"),
        );

        assert_eq!(iso_info.distro_type, DistroType::Unknown(String::new()));
        assert_eq!(iso_info.kernel_path, PathBuf::new());
        assert_eq!(iso_info.initrd_path, PathBuf::new());
        // Unrelated to detection, so a placeholder must pass these through
        // unchanged.
        assert_eq!(iso_info.file_name, "test.iso");
        assert_eq!(iso_info.file_path, PathBuf::from("/isos/test.iso"));
    }

    #[test]
    fn apply_boot_info_copies_every_shared_field() {
        let mut iso_info = IsoInfo::placeholder(
            "test.iso".to_string(),
            PathBuf::from("/isos/test.iso"),
            PathBuf::from("/run/pxe-boot/iso-mountpoint/test.iso"),
        );
        let boot_info = BootInfo {
            kernel_path: PathBuf::from("/boot/vmlinuz"),
            initrd_path: PathBuf::from("/boot/initrd"),
            distro_type: DistroType::Ubuntu,
            version: Some("24.04".to_string()),
            architecture: Some("amd64".to_string()),
            init_path: None,
        };

        iso_info.apply_boot_info(&boot_info);

        assert_eq!(iso_info.distro_type, DistroType::Ubuntu);
        assert_eq!(iso_info.kernel_path, PathBuf::from("/boot/vmlinuz"));
        assert_eq!(iso_info.initrd_path, PathBuf::from("/boot/initrd"));
    }

    fn minimal_config_json() -> serde_json::Value {
        serde_json::json!({
            "iso_folder_paths": ["/data/iso"],
            "tftp_root": "/srv/pxeboot",
            "runtime_root": "/run/pxe-boot",
            "dhcp_interfaces": [],
            "http": { "port": 1337 }
        })
    }

    #[test]
    fn minimal_config_parses() {
        let config: PxeBootConfig = serde_json::from_value(minimal_config_json()).unwrap();
        assert_eq!(config.tftp_root, PathBuf::from("/srv/pxeboot"));
    }

    #[test]
    fn unknown_top_level_field_is_rejected() {
        let mut json = minimal_config_json();
        json.as_object_mut()
            .unwrap()
            .insert("mount_port".to_string(), serde_json::json!(1338));

        let err = serde_json::from_value::<PxeBootConfig>(json).unwrap_err();
        assert!(
            err.to_string().contains("unknown field"),
            "expected an unknown-field error, got: {err}"
        );
    }

    #[test]
    fn unknown_dhcp_interface_field_is_rejected() {
        let mut json = minimal_config_json();
        json["dhcp_interfaces"] = serde_json::json!([{
            "id": 1,
            "name": "eth0",
            "gateway": "192.168.1.1",
            "default_iso": null,
            "default_script": null,
            "tftpp_root": "/typo",
        }]);

        let err = serde_json::from_value::<PxeBootConfig>(json).unwrap_err();
        assert!(
            err.to_string().contains("unknown field"),
            "expected an unknown-field error, got: {err}"
        );
    }

    #[test]
    fn unknown_http_field_is_rejected() {
        let mut json = minimal_config_json();
        json["http"] = serde_json::json!({ "port": 1337, "iso_port": 1338 });

        let err = serde_json::from_value::<PxeBootConfig>(json).unwrap_err();
        assert!(
            err.to_string().contains("unknown field"),
            "expected an unknown-field error, got: {err}"
        );
    }
}
